import os
import sys
import re
from enum import Enum
import random

# Add the parent directory of 'final_differential_test' to the Python path
# to allow importing from BaseRepoAdapter and DiffTestEngine.
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "../../..")))
from BaseRepoAdapter import BaseRepoAdapter, TestCase, FuzzHelper
from DiffTestEngine import DiffTestEngine

CASES_PER_CATEGORY = 50

# =====================================================================
# 1. Command Type Enum (Values are generic command structures)
# =====================================================================
class CmdCategory(Enum):
    """
    Enumerates the core functional commands of simplescript to be tested.
    Each enum value is a generic template representing the command structure.
    NOTE: The 'wasm' command is excluded as it requires TinyGo, which is not
    installed in the base environment per framework rules.
    """
    RUN = "simplescript run <file>"
    BUILD = "simplescript build <file>"


# =====================================================================
# 2. Repository Adapter Implementation
# =====================================================================
class SimpleScriptAdapter(BaseRepoAdapter):
    """
    Adapter for the simplescript CLI tool.
    Handles installation, test case generation, and output sanitization.
    """

    @property
    def base_image(self) -> str:
        """
        Return the Docker base image for the Go environment.
        """
        return "golang:latest"

    def sanitize_stdout(self, raw_stdout: str) -> str:
        """
        Sanitizes command output to remove volatile information like temporary
        file paths that can appear in Go panic traces or build outputs.
        """
        # Sanitize paths like /tmp/go-build... or /repo/repo_to_be_tested/...
        sanitized = re.sub(r'/(tmp|repo)/[^\s:]+', '<path>', raw_stdout)
        return super().sanitize_stdout(sanitized)

    def install_oracle(self, container) -> None:
        """
        Installs the oracle version of simplescript from GitHub according to strict rules.
        """
        cmd = "mkdir -p /repo && cd /repo && git clone https://github.com/VictorFrancelino/simplescript.git && cd simplescript && go install ."
        if container.exec_run(f"sh -c '{cmd}'").exit_code != 0:
            raise Exception("Oracle installation failed")

    def install_agent(self, container, local_agent_path: str) -> None:
        """
        Copies the local agent code into the container and installs it per strict rules.
        """
        container.exec_run("mkdir -p /repo")
        # The os.system call is part of the framework's design for copying files.
        if os.system(f"docker cp {local_agent_path} {container.id}:/repo/repo_to_be_tested") != 0:
            raise Exception("Failed to copy agent code to container.")

        cmd = "cd /repo/repo_to_be_tested && go install -buildvcs=false ."
        if container.exec_run(f"sh -c '{cmd}'").exit_code != 0:
            raise Exception("Agent installation failed")

    def _generate_ss_script(self, is_edge_case: bool) -> str:
        """
        Helper method to generate SimpleScript code for test cases.
        Generates valid code for happy paths and malformed/invalid code for edge cases.
        """
        if is_edge_case:
            roll = random.randint(0, 5)
            if roll == 0:
                # Use a potentially disruptive string as file content
                return FuzzHelper.get_evil_string()
            elif roll == 1:
                # Empty file
                return ""
            elif roll == 2:
                # Script with a disruptive string inside 'say'
                return f"say('{FuzzHelper.get_evil_string()}')"
            elif roll == 3:
                # Type mismatch error
                return "var a: int = 'this is not an integer'"
            elif roll == 4:
                # Re-assigning a constant
                return "const my_const: float = 3.14\nmy_const = 9.9"
            else:
                # Using an undeclared variable
                return "say(undeclared_var)"
        else:
            # Generate a syntactically valid script
            lines = [
                "// Auto-generated by fuzzer",
                f"const lang_name: str = '{FuzzHelper.get_string(5, 15)}'",
                f"var counter: int = {FuzzHelper.get_int(0, 100)}",
                f"say('Initial value:', counter, lang_name)",
                f"var total: float = {FuzzHelper.get_float(1.0, 5.0)}",
                f"for i in 0..{FuzzHelper.get_int(2, 8)} {{",
                f"  total = total + {FuzzHelper.get_float(0.1, 2.0)}",
                f"}}",
                f"say('Final total:', total)"
            ]
            return "\n".join(lines)

    # =====================================================================
    # 3. Standardized Test Case Generator
    # =====================================================================
    def generate_test_cases(self) -> list[TestCase]:
        """
        Generates a list of TestCase objects for differential testing.
        """
        cases = []
        for category in CmdCategory:
            for i in range(CASES_PER_CATEGORY):
                try:
                    # Designate one case in five as an edge/malicious case
                    is_edge_case = (i == 0)
                    
                    file_name = f"fuzz_{category.name.lower()}_{i}.ss"
                    content = self._generate_ss_script(is_edge_case)
                    
                    command = f"simplescript {category.name.lower()} /test_data/{file_name}"

                    cases.append(TestCase(
                        command=command,
                        category=category.value,
                        mount_files={file_name: content}
                    ))
                except Exception as e:
                    # This ensures that if one case generation fails, the whole process doesn't stop.
                    print(f"Warning: Failed to generate test case for {category.name} index {i}: {e}", file=sys.stderr)
                    continue
        return cases

# =====================================================================
# 4. Main Entry
# =====================================================================
if __name__ == "__main__":
    local_repo_path = os.path.join(os.path.dirname(__file__), "repo_to_be_tested")
    adapter = SimpleScriptAdapter()
    engine = DiffTestEngine(adapter=adapter, agent_local_path=local_repo_path)
    engine.run(output_json_path=os.path.join(os.path.dirname(__file__), "output.json"))