import os
import sys
import re
import random
from enum import Enum
from typing import List

# Add the root directory of the framework to the Python path
sys.path.append(os.path.abspath("../../.."))
from BaseRepoAdapter import BaseRepoAdapter, TestCase, FuzzHelper
from DiffTestEngine import DiffTestEngine

# =====================================================================
# 1. Command Type Enum (Values are generic command structures)
# =====================================================================
class CmdCategory(Enum):
    """
    Enumerates the core functional commands of the 'reqtext' CLI tool.
    The value of each enum member is a generic string template of the command.
    Interactive commands like 'editor' are excluded.
    """
    INIT = "reqt init <project_name>"
    CLEAN = "reqt clean"
    ADD_ITEM = "reqt add-item <item_name>"
    ADD_AFTER = "reqt add-after <outline_number> <title>"
    DELETE = "reqt delete <outline_number>"
    MAKE_CHILDREN = "reqt make-children <outline_number>"
    MAKE_SIBLING = "reqt make-sibling <outline_number>"
    EDIT_TITLE = "reqt edit-title <outline_number> <new_title>"
    SET_STATUS = "reqt set-status <outline_number> <status>"
    GENERATE_README = "reqt generate-readme"

# =====================================================================
# 2. Repository Adapter Implementation for 'reqtext'
# =====================================================================
class ReqtextAdapter(BaseRepoAdapter):
    @property
    def base_image(self) -> str:
        """Specifies the Docker base image for the testing environment."""
        return "node:latest"

    @property
    def ignore_patterns(self) -> List[str]:
        """Add patterns for npm cache and logs to the base ignore list."""
        base_patterns = super().ignore_patterns
        base_patterns.extend([
            r"^/root/\.npm(/|$)",
            r".*npm-debug\.log.*"
        ])
        return base_patterns

    def sanitize_stdout(self, raw_stdout: str) -> str:
        """
        Removes volatile information (timestamps, local paths) from the tool's output
        to ensure stable diffing.
        """
        # Remove volatile timestamp from "README.md generated by ... on <timestamp>"
        sanitized = re.sub(r"on \d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z", "on [TIMESTAMP]", raw_stdout)
        # Remove volatile project path from init message
        sanitized = re.sub(r"Project initialized at .*/", "Project initialized at [PATH]/", sanitized)
        return super().sanitize_stdout(sanitized)

    def install_oracle(self, container) -> None:
        """Clones and installs the oracle version from GitHub."""
        cmd = "mkdir -p /repo && cd /repo && git clone https://github.com/fred-terzi/reqtext.git && cd reqtext && npm install && npm install -g ."
        if container.exec_run(f"sh -c '{cmd}'").exit_code != 0:
            raise Exception("Oracle Installation Failed")

    def install_agent(self, container, local_agent_path: str) -> None:
        """Copies and installs the local agent version."""
        container.exec_run("mkdir -p /repo")
        # Use docker cp via os.system as it's a reliable way to copy files into a running container
        os.system(f"docker cp {local_agent_path} {container.id}:/repo/repo_to_be_tested")
        cmd = "cd /repo/repo_to_be_tested && npm install && npm install -g ."
        if container.exec_run(f"sh -c '{cmd}'").exit_code != 0:
            raise Exception("Agent Installation Failed")

    def _shell_escape(self, s: str) -> str:
        """Safely escapes a string for use in a shell command."""
        return "'" + s.replace("'", "'\\''") + "'"

    # =====================================================================
    # 3. Standardized Test Case Generator
    # =====================================================================
    def generate_test_cases(self) -> List[TestCase]:
        """
        Generates a list of test cases covering all command categories,
        integrating both normal and edge/malicious inputs.
        """
        cases: List[TestCase] = []
        CASES_PER_CATEGORY = 50
        PROJECT_NAME = "fuzz_project"
        PROJECT_FILE = f"{PROJECT_NAME}.reqt.md"
        README_FILE = "README.md"

        # Common prep scripts for commands that need a project to exist
        prep_init_only = f"reqt init {self._shell_escape(PROJECT_NAME)}"
        prep_with_items = f"{prep_init_only} && reqt add-item 'Item One' && reqt add-item 'Item Two'"

        for category in CmdCategory:
            for i in range(CASES_PER_CATEGORY):
                is_edge_case = (i == 0)
                
                try:
                    tc = None
                    # --- Command Generation Logic ---
                    if category == CmdCategory.INIT:
                        project_name = FuzzHelper.get_evil_string() if is_edge_case else FuzzHelper.get_string(5, 15)
                        tc = TestCase(
                            command=f"reqt init {self._shell_escape(project_name)}",
                            category=category.value
                        )

                    elif category == CmdCategory.CLEAN:
                        if is_edge_case:
                            # Test the core purpose of 'clean': fixing a manually/AI-edited file.
                            # We mount a malformed file and expect the tool to fix it.
                            malformed_content = (
                                f"<!-- reqt: {{\"version\":\"0.1.0\",\"source\":\"{PROJECT_FILE}\"}} -->\n"
                                f"0: {PROJECT_NAME}\n"
                                "<!-- reqt: {{\"id\":\"id_1\",\"status\":\"IN DEV\",\"author\":\"test\",\"created\":\"2024-01-01T00:00:00.000Z\"}} -->\n"
                                "1: An existing item\n"
                                "- A new item without an ID"  # This is what 'clean' should fix
                            )
                            tc = TestCase(
                                command=f"reqt clean && cat {PROJECT_FILE}",
                                category=category.value,
                                mount_files={PROJECT_FILE: malformed_content}
                            )
                        else:
                            # Normal case: run clean on a valid project (should be a no-op).
                            tc = TestCase(
                                command=f"reqt clean && cat {PROJECT_FILE}",
                                category=category.value,
                                prep_script=prep_init_only
                            )

                    elif category == CmdCategory.ADD_ITEM:
                        item_name = FuzzHelper.get_evil_string() if is_edge_case else FuzzHelper.get_string(5, 20)
                        tc = TestCase(
                            command=f"reqt add-item {self._shell_escape(item_name)} && cat {PROJECT_FILE}",
                            category=category.value,
                            prep_script=prep_init_only
                        )

                    elif category == CmdCategory.ADD_AFTER:
                        title = FuzzHelper.get_evil_string() if is_edge_case else FuzzHelper.get_string(5, 20)
                        outline_id = FuzzHelper.get_evil_string() if is_edge_case else random.choice(['1', '2'])
                        command = f"reqt add-after {self._shell_escape(outline_id)} {self._shell_escape(title)}"
                        tc = TestCase(f"{command} && cat {PROJECT_FILE}", category.value, prep_with_items)

                    elif category == CmdCategory.DELETE:
                        outline_id = FuzzHelper.get_evil_string() if is_edge_case else random.choice(['1', '2'])
                        command = f"reqt delete {self._shell_escape(outline_id)}"
                        tc = TestCase(f"{command} && cat {PROJECT_FILE}", category.value, prep_with_items)

                    elif category == CmdCategory.MAKE_CHILDREN:
                        outline_id = FuzzHelper.get_evil_string() if is_edge_case else '2'  # Make item '2' a child of item '1'
                        command = f"reqt make-children {self._shell_escape(outline_id)}"
                        tc = TestCase(f"{command} && cat {PROJECT_FILE}", category.value, prep_with_items)

                    elif category == CmdCategory.MAKE_SIBLING:
                        # Ensure a child (1.1) exists to be promoted
                        prep = prep_with_items + " && reqt make-children 2"
                        outline_id = FuzzHelper.get_evil_string() if is_edge_case else '1.1'  # Promote the child
                        command = f"reqt make-sibling {self._shell_escape(outline_id)}"
                        tc = TestCase(f"{command} && cat {PROJECT_FILE}", category.value, prep)

                    elif category == CmdCategory.EDIT_TITLE:
                        new_title = FuzzHelper.get_evil_string() if is_edge_case else FuzzHelper.get_string(5, 20)
                        outline_id = FuzzHelper.get_evil_string() if is_edge_case else '1'
                        command = f"reqt edit-title {self._shell_escape(outline_id)} {self._shell_escape(new_title)}"
                        tc = TestCase(f"{command} && cat {PROJECT_FILE}", category.value, prep_with_items)

                    elif category == CmdCategory.SET_STATUS:
                        status = FuzzHelper.get_evil_string() if is_edge_case else random.choice(["NEW", "IN_DEV", "DONE", "REJECTED"])
                        outline_id = FuzzHelper.get_evil_string() if is_edge_case else '1'
                        command = f"reqt set-status {self._shell_escape(outline_id)} {self._shell_escape(status)}"
                        tc = TestCase(f"{command} && cat {PROJECT_FILE}", category.value, prep_with_items)

                    elif category == CmdCategory.GENERATE_README:
                        command = f"reqt generate-readme && cat {README_FILE}"
                        if is_edge_case:
                            # Test with an evil project name, which might cause init or readme generation to fail
                            evil_name = FuzzHelper.get_evil_string()
                            prep = f"reqt init {self._shell_escape(evil_name)} && reqt add-item 'Test Item'"
                            # Safeguard cat in case README.md is not created
                            command += " || true"
                        else:
                            prep = prep_with_items
                        tc = TestCase(command, category.value, prep)

                    if tc:
                        cases.append(tc)

                except Exception as e:
                    print(f"Warning: Failed to generate test case for {category.name} (i={i}). Error: {e}")
                    continue
        return cases

# =====================================================================
# 4. Main Entry Point
# =====================================================================
if __name__ == "__main__":
    local_repo_path = os.path.join(os.path.dirname(__file__), "repo_to_be_tested")
    adapter = ReqtextAdapter()
    engine = DiffTestEngine(adapter=adapter, agent_local_path=local_repo_path)
    engine.run(output_json_path=os.path.join(os.path.dirname(__file__), "output.json"))